plan/urls.py
from django.urls import path
from .views import *


urlpatterns = [

   path('', MobilePlanHome.as_view(), name='mobileplans'),
   path('operators/', PlanView.as_view(),name='operators'),
   path('ajax/', ajax_result, name='plan_ajax'),
   path('ajax-list/', PlanPhoneList.as_view(), name='plan_ajax_list'),
   path('plan-count/', plan_count, name='plan_count'),
   path('mobile_plan_count/', mobile_internet_count, name='mobile_plan_count'),
   # path('<str:phone_slug>/<str:phone_name>/<str:phone_media>/', PlanView.as_view(), name='operator-mob'),
   # path('', PlanView.as_view(), name='operators_phone'),
   path('device/<pk>/', DeviceDetailView.as_view(), name='devicedetailpk'),
   path('device/<pk>/<param>/', DeviceDetailView.as_view(), name='devicedetail'),
   path('operators/<slug:slug>/', PlanDetailView.as_view(), name='operatordetail'),
   path('ajax-plan-admin/', query_operator_country, name='operator_country'),
   path('ajax-plan-country-admin/',query_plan_country,name='plan_country_admin'),
   path('ajax-plan-country-phone-admin/', query_phone_plan_country, name='plan_phone_country_admin'),
   path('ajax-device-installment-admin/', query_device_installment, name='plan_device_installment_admin')

]

planbaker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

admin.site.site_header = "Plan Baker Admin"
admin.site.site_title = "Plan Baker Admin Portal"
admin.site.index_title = "Welcome to Plan Baker Admin Portal"
urlpatterns = [





]
urlpatterns += i18n_patterns(

    #path('', TemplateView.as_view(template_name="home.html"),name='home'),
    path('', include('homepage.urls')),
    path('search/',include('search.urls')),
    #path('phone/',include('phone.url'),name='phone'),
    path('phones/', include('phone.urls')),
    path('ads/', include('advertisement.urls')),
    path('registration/', include('user.urls')),
    path('register/', TemplateView.as_view(template_name="register_login.html"), name='sign_up_in'),
    path('mobile_internet/', include('mobile_internet.urls')),
    path('fixed_internet/', include('fixed_internet.urls')),

    path('buyphones/', TemplateView.as_view(template_name="planbaker_04.html"),name='buyphones'),
    path('operators/', include('plan.urls')),
    #path('operators/', TemplateView.as_view(template_name="Planbaker_03.html"), name='operators'),
    #path('viewoperators/', TemplateView.as_view(template_name="viewoperator.html"), name='viewoperators'),
    path('mobileplans/', include('plan.urls')),

    path('adsl/', TemplateView.as_view(template_name="planbaker_05.html"),name='adsl'),
    path('add/', TemplateView.as_view(template_name="404.html"),name='add'),
    path('admin/', admin.site.urls),
    path('survey/', include('survey.urls')),
    path('test/',include('pages.urls')),
)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/forms.py
from django import forms
from .widgets import RangeSlider,PayTypeFilter,CalculationMethodAdminWidgets
from .models import CalculationMethod


# <input type="range" min="0" max="100" value="0" class="slider" id="msgRange">


class PlanForm(forms.Form):

    def __init__(self, *args, **kwargs):
        only_sim_param = None
        if len(args) > 0:
            try:
                if 'only_sim' in args[0]:
                    only_sim_param = args[0].get('only_sim', None)
            except KeyError:
                pass

        session = kwargs.pop("session",None)
        qs = kwargs.pop("qs",None)
        super(PlanForm,self).__init__(*args,**kwargs)
        self.fields['pay_type'] = forms.CharField(widget=PayTypeFilter(qs=qs))
        self.fields['price_range'] = forms.IntegerField(widget=RangeSlider(session=session,qs=qs,
                                                                           price_from=self.__class__.__name__,
                                                                           only_sim_param=only_sim_param))

    phone_name = forms.CharField(widget=forms.HiddenInput(attrs={'class': 'plan_form_class',
                                                                 'id': 'selected_phone_name_id', 'value': ""}))
    phone_slug = forms.CharField(widget=forms.HiddenInput(attrs={'class': 'plan_form_class',
                                                                 'id': 'selected_phone_slug_id', 'value': ""}))
    phone_media = forms.CharField(widget=forms.HiddenInput(attrs={'class': 'plan_form_class',
                                                                  'id': 'selected_phone_media_id', 'value': ""}))
    selected_network = forms.CharField(widget=forms.HiddenInput(attrs={'class': 'plan_form_class',
                                                                       'id': 'selected_network_id', 'value': ""}))
    order_by = forms.CharField(widget=forms.HiddenInput(attrs={'class': 'plan_form_class',
                                                               'id': 'sorting_id', 'value': "",
                                                               "display_val": "Sort By"}))
    messages = forms.IntegerField(widget=RangeSlider(session=None,qs=None,price_from=None, only_sim_param=None))
    minutes = forms.IntegerField(widget=RangeSlider(session=None,qs=None,price_from=None, only_sim_param=None))
    data = forms.IntegerField(widget=RangeSlider(session=None,qs=None,price_from=None, only_sim_param=None))

    only_sim = forms.BooleanField(required=False, widget=forms.CheckboxInput(attrs={'class': 'plan_form_class'}))
    # pay_type = forms.CharField(widget=PayTypeFilter(num))


class CalculationMethodAdminForm(forms.ModelForm):
    class Meta:
        model = CalculationMethod
        fields = "__all__"
        widgets = {
            'expression' :CalculationMethodAdminWidgets
        }



# class CountryForm(forms.ModelForm):
#     class Meta:
#         model = Country
#
#     def clean_featured(self):
#         featuredCount = Country.objects.filter(featured=True).count()
#
#         if featuredCount >= 5 and self.cleaned_data['featured'] is True:
#             raise forms.ValidationError("5 Countries can be featured at most!")
#         return self.cleaned_data['featured']
#

plan/views.py
import json
from django.views.generic.list import ListView
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from django.views.generic import DetailView, TemplateView
from django.db.models import Q,Count
from django.core.exceptions import ObjectDoesNotExist,MultipleObjectsReturned
from django.http import JsonResponse
from django.http import HttpResponse, Http404
from django.core import serializers
from el_pagination.views import AjaxListView
from phone.models import Country
from plan.forms import PlanForm
from homepage.utils import get_context_obj
from utils.util import get_planphone_count
from .utils import get_plan_phone_image_path,donut_calculation,donut_calculation_plan_detail
from .models import Plan,PlanPhone,DeviceRam,PlanDevice,operators,DeviceInstallment
from .decorators import sort_plan


class MobilePlanHome(TemplateView):
    template_name = 'plan/mobile_plan_home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        con = get_context_obj(self.request)
        context['obj'] = con['obj']
        context['country'] = con['country']

        context['form_class'] = PlanForm()
        return context


# class PlanView(ListView):
#     model = Plan
#     paginate_by = 40
#     context_object_name = 'plans'
#     template_name = 'plan/plan_home.html'
#
#     def __init__(self):
#         self.form_class = None
#
#         super(PlanView, self).__init__()
#
#     def get_queryset(self):
#         sort = self.request.GET.get("order_by")
#         # pay_type = self.form_class['pay_type'].value()
#         # selected_network = self.form_class['selected_network'].value()
#         # price_range = self.form_class['price_range'].value()
#         pay_type = self.request.GET.get("pay_type")
#         selected_network = self.request.GET.get("selected_network")
#         price_range = self.request.GET.get("price_range")
#         data = int(self.request.GET.get("data",0))
#         minutes = int(self.request.GET.get("minutes",0))
#         phone_slug = self.request.GET.get("phone_slug")
#         try:
#             country = self.request.session.get('country')
#         except:
#             country = "SA"
#
#         try:
#             # only_sim = self.form_class['only_sim'].value()
#             only_sim = self.request.GET.get("only_sim")
#             if only_sim:
#                 qs = Plan.mobile_plan_objects.filter(Q(plan_type__exact=1),
#
#                                          Q(data__donut_data_val__gte=data*1000),
#                                          Q(call__donut_call_val__gte=minutes))
#
#             else:
#
#                 qs = Plan.mobile_plan_objects.filter(
#
#                                      Q(data__donut_data_val__gte=data*1000),
#                                      Q(call__donut_call_val__gte=minutes))
#
#
#             # qs.get(donut_message_val__gte = self.form_class['message'].value())
#             # User.objects.filter(userprofile__level__gte=0)
#         except ValueError:
#             qs = Plan.mobile_plan_objects.all()
#         if selected_network:
#             qs = qs.filter(operator_id__operator=selected_network)
#         if price_range:
#
#             qs = qs.filter(id__in=[q.id for q in qs if q.mf_value >= int(price_range)])
#
#         if sort:
#
#             if sort=="fee":
#                 pk_name = ('id' if not getattr(Plan._meta, 'pk', None)
#                            else Plan._meta.pk.attname)
#                 pk_name = '%s.%s' % (Plan._meta.db_table, pk_name)
#                 pk_list = [q.id for q in sorted(qs, key=lambda qs: qs.mf_value)]
#                 clauses = ' '.join(['WHEN %s=%s THEN %s' % (pk_name,pk, i) for i, pk in enumerate(pk_list)])
#                 ordering = 'CASE %s END' % clauses
#                 qs = qs.filter(pk__in=pk_list).extra(
#                     select={'ordering': ordering}, order_by=('ordering',))
#
#             elif sort=="-fee":
#                 pk_name = ('id' if not getattr(Plan._meta, 'pk', None)
#                            else Plan._meta.pk.attname)
#                 pk_name = '%s.%s' % (Plan._meta.db_table, pk_name)
#
#                 pk_list = [q.id for q in sorted(qs, key=lambda qs: qs.mf_value, reverse=True)]
#
#                 clauses = ' '.join(['WHEN %s=%s THEN %s' % (pk_name, pk, i) for i, pk in enumerate(pk_list)])
#                 ordering = 'CASE %s END' % clauses
#                 qs = qs.filter(pk__in=pk_list).extra(
#                     select={'ordering': ordering}, order_by=('ordering',))
#             else:
#                 qs=qs.order_by(sort)
#         if phone_slug and not only_sim:
#             qs = qs.filter(id__in=DeviceInstallment.objects.filter(plan__in=qs,phone__device_phone__id=int(phone_slug)).values('plan'))
#         qs =qs.filter(country__country_code=country)
#
#         self.form_class = PlanForm(self.request.GET, qs=qs,session = self.request.session)
#         if pay_type:
#             qs = qs.filter(pay_type__exact=pay_type)
#
#
#
#
#
#         return qs
#
#     def get(self, request, *args, **kwagrs):
#         return super(PlanView, self).get(request, *args, **kwagrs)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         con = get_context_obj(self.request)
#         context['obj'] = con['obj']
#         context['country'] = con['country']
#         context['form_class'] = self.form_class
#
#         return donut_calculation(context)

class PlanView(AjaxListView):
    # model = Plan
    # paginate_by = 40
    # context_object_name = 'plans'
    # template_name = 'plan/plan_home.html'
    model = Plan

    context_object_name = 'plans'
    template_name = 'plan/plan_home.html'
    page_template = 'plan/plan_home_list.html'

    def __init__(self):
        self.form_class = None

        super(PlanView, self).__init__()

    @sort_plan
    def sorting(self,*args,**kwargs):
        return kwargs['qs']

    def get_queryset(self):

        sort = self.request.GET.get("order_by")
        # pay_type = self.form_class['pay_type'].value()
        # selected_network = self.form_class['selected_network'].value()
        # price_range = self.form_class['price_range'].value()
        pay_type = self.request.GET.get("pay_type")
        selected_network = self.request.GET.get("selected_network")
        price_range = self.request.GET.get("price_range")
        data = int(self.request.GET.get("data",0))
        minutes = int(self.request.GET.get("minutes",0))
        phone_slug = self.request.GET.get("phone_slug")
        messages = int(self.request.GET.get("messages",0))
        only_sim = self.request.GET.get("only_sim",None)

        try:
            country = self.request.session.get('country')
        except:
            country = "SA"

        try:
            # only_sim = self.form_class['only_sim'].value()
            qs = Plan.mobile_plan_objects.filter(
                                                 Q(message__donut_message_val__gte=messages),

                                                 Q(data__donut_data_val__gte=data * 1000),
                                                 Q(call__donut_call_val__gte=minutes))

            # if only_sim:
            #     qs = Plan.mobile_plan_objects.filter(Q(plan_type__exact=1),
            #                                          Q(message__donut_message_val__gte=messages),
            #
            #                              Q(data__donut_data_val__gte=data*1000),
            #                              Q(call__donut_call_val__gte=minutes))

        except ValueError:
            qs = Plan.mobile_plan_objects.all()
        if only_sim:
            qs = qs.filter(Q(plan_type__exact=1))
        if selected_network:
            qs = qs.filter(operator_id__operator=selected_network)
        if price_range:

            qs = qs.filter(id__in=[q.id for q in qs if q.mf_value >= int(price_range)])

        if sort:
            qs = self.sorting(sort=sort, qs=qs, model=self.model)

            # if sort=="fee":
            #     pk_name = ('id' if not getattr(Plan._meta, 'pk', None)
            #                else Plan._meta.pk.attname)
            #     pk_name = '%s.%s' % (Plan._meta.db_table, pk_name)
            #     pk_list = [q.id for q in sorted(qs, key=lambda qs: qs.mf_value,reverse=False)]
            #     clauses = ' '.join(['WHEN %s=%s THEN %s' % (pk_name,pk, i) for i, pk in enumerate(pk_list)])
            #     print(clauses,"planclauses")
            #     ordering = 'CASE %s END' % clauses
            #     qs = qs.filter(pk__in=pk_list).extra(
            #         select={'ordering': ordering}, order_by=('ordering',))
            #
            # elif sort=="-fee":
            #     pk_name = ('id' if not getattr(Plan._meta, 'pk', None)
            #                else Plan._meta.pk.attname)
            #     pk_name = '%s.%s' % (Plan._meta.db_table, pk_name)
            #
            #     pk_list = [q.id for q in sorted(qs, key=lambda qs: qs.mf_value, reverse=True)]
            #
            #     clauses = ' '.join(['WHEN %s=%s THEN %s' % (pk_name, pk, i) for i, pk in enumerate(pk_list)])
            #     ordering = 'CASE %s END' % clauses
            #     qs = qs.filter(pk__in=pk_list).extra(
            #         select={'ordering': ordering}, order_by=('ordering',))
            # else:
            #     qs=qs.order_by(sort)
        if phone_slug and not only_sim:
            qs = qs.filter(id__in=DeviceInstallment.objects.filter(plan__in=qs,phone__device_phone__id=int(phone_slug)).values('plan'))
        qs =qs.filter(country__country_code=country)

        self.form_class = PlanForm(self.request.GET, qs=qs,session = self.request.session)
        if pay_type:
            qs = qs.filter(pay_type__exact=pay_type)
        print(qs,"printing qs for plan")
        return qs

    def get(self, request, *args, **kwagrs):

templates/plan/device_gallery.html
{% load static %}
{% load media_url %}
<div class="planVndr_products_slider">
						<div class="mobile_availability_hdrDiv">
                            <center><h3>Image Gallery</h3></center>
						</div>
						<div class="top_products_slides planVndr_products_list_slider carousel">
                            {% for ob in object.planphoneimages.all %}
							<div class="planVndr_products_list_slides_div">
								<div class="planVndr_products_list_slidesImg">
									<img src="{{ob.image|operator_logo}}" class="img-responsive" alt="Slider1 Image">
								</div>

							</div>
                            {%endfor%}


						</div>
</div>

templates/plan/operator_details.html
<div class="dropdown netwrk-dropdwn">
										  <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
												  style="width: 100%;overflow: hidden;white-space: nowrap;display: block; text-overflow: ellipsis;" aria-expanded="true">
										    All
										    <span class="caret"></span>
										  </button>
										  <ul class="dropdown-menu" style="list-style-position: inside;white-space: nowrap;overflow: hidden;text-overflow: ellipsis;">
                                              <li><a class="net_cl"   value="">All</a></li>
                                              {% for op in context%}
										    <li style="white-space:initial;hyphens:auto;"><a class="net_cl"   value="{{op.operator_id__operator}}">{{op.operator_id__operator}}</a></li>

                                              {% endfor %}
										  </ul>
										</div>

templates/plan/operator_images.html
{% for op in context%}
<li><img class="img-responsive" alt="verizon" src="{{media}}{{op.operator_id__image}}"></li>
{% endfor %}

templates/plan/phone_list.html
{% include page_template %}

{% block js %}

    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="/static/el-pagination/js/el-pagination.js"></script>
    <script>$.endlessPaginate({

            paginateOnScrollMargin: 20,

        });</script>

{% endblock %}

templates/plan/phone_list_page.html
{% load el_pagination_tags %}

{% load media_url %}

{% paginate 40 phone_list %}
	         			<div class="filtered_products_list slctmodal_mob_list ">

							<div id="form-modal-body" class="top_products_slides top_products_slides_append row">




{% for entry in phone_list %}
      <div class="col-md-2 col-xs-6 col-sm-4">
										<div class="thumb-wrapper">
											<div class="img-box">
											<a onclick=sendinfo('{{entry.name|split}}','{{entry|media_url}}','{{entry.id}}')><img src="{{entry|media_url}}" class="img-responsive img-fluid" alt="slider Image 1"></a>
											</div>
											<div class="thumb-content">
												<div style="height: 55px;padding:5px"><h5 class="text-capitalize" style="font-size: 10px;font-weight: bold;">{{entry.name}}</h5></div>
												<div>

                                                    {{entry|plan_count_for_device}}
                                                </div>
											</div>

										</div>

									</div>

{% endfor %}
								</div>


 					</div>

{% show_more %}

templates/plan/plan_home.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load media_url %}
{% load plan_tags %}
{% block title %}
    Phones
{% endblock %}
{% block content %}
	<section class="filterBlock_section">

		<div class="container filterBlock_container">
			<div class="row">
				<div class="col-sm-6 floatleft">
					<h2 class="main-hdng"> <span class="choose_best_plans_for"> Cell Phone Plans in </span>
					<span class="mobilephonr_trans"> {{country.country_full_name}}</span> </h2>
				</div>
				<div class="col-sm-6 floatright">
					<ul class="company-clients-logos">

                        {% operator_images "plan" %}
                    </ul>
				</div>
			</div>
<form method="GET" class="plan_home_form_id" action="{% url 'operators' %}">
			<div class="row">

				<div class="col-sm-3 ">
					<div class="row select_phone_sec">
						<div class="select_phone_div">
							<div class="img-box">

								<a href="#" class="see_selectmobile_link" >
								<img src="{% if form_class.phone_media.value%}{{form_class.phone_media.value}}{%else%}{% static 'images/mobile.png'%}{%endif%}" class="img-responsive img-fluid" alt="slider Image 1"  style="max-width:100%;">
								</a>

							</div>
							<div class="remove-phone-div img-block">
			<a onclick="sendslug('specs')">Specs</a>/<a onclick="sendslug('image')"> Gallery</a>/<a onclick="removephone()"> Remove</a>

									</div>
						</div>
						<div >
								<p>Selected Phone</p>
							{{form_class.phone_name}}
							{{form_class.phone_media}}
							{{form_class.phone_slug}}
							{{form_class.order_by}}
							{{form_class.selected_network}}




							<h5>{% if form_class.phone_name.value%}<b>{{form_class.phone_name.value}}</b>{%else%}No Phone Selected{%endif%}</h5>
								<!--<div class="dropdown netwrk-dropdwn">-->
										  <!--<button class="btn dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">-->
										    <!--Options/Add a line-->
										    <!--<span class="caret"></span>-->
										  <!--</button>-->
										  <!--<ul class="dropdown-menu" >-->
										    <!--<li><a href="#">Action</a></li>-->
										    <!--<li><a href="#">Another action</a></li>-->
										    <!--<li><a href="#">Something else here</a></li>-->
										    <!--<li><a href="#">Separated link</a></li>-->
										  <!--</ul>-->

								<!--</div>-->
							<div>Only SIM: {{form_class.only_sim}}</div>{{ form_class.order_by.display_val}}
				        </div>
					</div>
				</div>
				<div class="col-sm-9 horizontal-slider">
								<div class="slidecontainer">
									<p id="data_text"><span class="data_trans">Data </span>
										{{form_class.data}}
										<!--<span id="dataRangeval"></span><span>GB </span><a href="#"></a></p>-->
									<!--<div>-->
								  	<!--<input type="range" min="100" max="1000" value="500" class="slider" id="dataRange">-->
								  	<!--</div>-->
								</div>
								<div class="slidecontainer">
								  <p><span class="minute_trans">Minutes</span>
									  {{form_class.minutes}}
									  <!--<span id="minutesRangeval"></span><a href="#"></a></p>-->
								  <!--<input type="range" min="100" max="1000" value="500" class="slider" id="minutesRange">-->
								</div>
								<div class="slidecontainer">
								  <p><span class="msg_trans">Price</span>
									  {{form_class.price_range}}
									  <!--<span id="msgRangeval"></span><a href="#"></a></p>-->
								  <!--<input type="range" min="100" max="1000" value="500" class="slider" id="msgRange">-->
								</div>
				</div>
				<!--<div class="col-sm-2 all_filter_div">-->
					<!--<p>Apply Filters</p>-->
					<!--<button class="btn add_filter_btn"><i class="flaticon-add-plus-button"></i></button>-->
				<!--</div>-->

			</div>

			<div class="row filter_button_sec" style="padding:15px;">
				<div class="col-sm-6 fliter_btns_div">


					{{form_class.pay_type}}


				</div>
				<div class="col-sm-6 fliter_actions_btn_div">
					<div class="dropdown">


					</div>
					<div class="dropdown">

										  <button class="btn dropdown-toggle main_btn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
										    {{ form_class.order_by.value|display }}
										    <span class="caret"></span>
										  </button>
										  <ul class="dropdown-menu" >

										    <li><a onclick="sendsort('fee')">Lowest Price</a></li>
										    <li><a onclick="sendsort('-fee')">Highest Price</a></li>
										    <li><a onclick="sendsort('-data__donut_data_val')">Maximum Data</a></li>
											<li><a onclick="sendsort('-call__donut_call_val')">Maximum Minutes</a></li>

										  </ul>
					</div>
					<button class="main_btn text-capitalize share_btn"><i class="flaticon-share"></i></button>
				</div>

			</div>
</form>
		</div>

	</section>

	<section class="load_plans">
		<div class="container load_plans_container">


			{% include page_template%}


		</div>
	</section>

<!--	<div class="load_more_div">-->
<!--		<div class="container">-->
<!--			<div class="load_more_btn_div">-->
<!--				<button disabled class="load_more_btn btn">Load More<span class="load_more_icon"><img class="img-responsive" alt="Load More" src="{% static 'images/load_more_icon.png'%}"></span></button>-->
<!--			</div>-->
<!--		</div>-->
<!--	</div>-->
<div class="modal fade custom_seeSpecModal" id="seeDeviceSpec" role="dialog">
	    <div class="modal-dialog modal-lg">

	      <!-- Modal content-->
	      <div class="modal-content ">
	        <div class="modal-header">
	          <h4 class="modal-title">{{details.slug}}</h4>

	          <!--<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>-->
				<button type="button" class="btn btn-default close1" data-dismiss="modal" aria-label="Close"><i class="fa fa-times fa-lg" aria-hidden="true"></i></button>
	        </div>
	        <div class="modal-body scrollPrdct_mdl" id="seeDeviceId">

	        </div>
	      </div>

	    </div>
	  </div>

	{% endblock %}






{% block extra_script %}
{% include "specificationModal.html" %}

<script src="/static/el-pagination/js/el-pagination.js"></script>
    <script>$.endlessPaginate({

            paginateOnScrollMargin: 20,

        });</script>
<script >

function sendslug(param){
id = $('#selected_phone_slug_id').val();
param = param
var url_mask = "{% url 'devicedetail' 12345 678 %}".replace(/12345/, id).replace(/678/, param);
console.log(url_mask)
$('#seeDeviceId').load(url_mask, function () {
                    $('#seeDeviceSpec').modal('toggle');
                    $('.modal-title').text(name);
                    //formAjaxSubmit('#form-modal-body form', '#form-modal');
                });
}



	// Slider script
function sendsort(field) {
    $('#sorting_id').val(field);
    searchForm = $(".plan_home_form_id");
    searchForm.submit();

}

function removephone() {
    $('#selected_phone_name_id').val("")
    $('#selected_phone_media_id').val("")
    $('#selected_phone_slug_id').val("")


    $('.remove-phone-div').css("display", "none");
    var el = $('.see_selectmobile_link img');
    el.attr("src", "{% static 'images/mobile.png'%}");
    el.attr("onmouseover", "this.src=\'{% static 'images/mobilenewh.png'%}\'");
    el.attr("onmouseout", "this.src=\'{% static 'images/mobile.png'%}\'");

    searchForm = $(".plan_home_form_id");
    searchForm.submit()

}



$(document).ready(function() {
    var name_val = $('#selected_phone_name_id').val()
    if (name_val) {
        $('.remove-phone-div').css("display", "inline-block");
        $('#id_only_sim').prop("disabled", true);
    }
    if($('#id_only_sim').prop('checked')){
		$('.see_selectmobile_link').css("pointer-events","none").css("cursor","default");

	}
	else{
		$('.see_selectmobile_link').removeAttr("style");
	}



    searchForm = $(".plan_home_form_id");
    searchInput = searchForm.find("input");


    var typingTimer;
    var typingInterval = 1500;

    searchInput.change(function(event) {

        clearTimeout(typingTimer);
        typingTimer = setTimeout(submitform(searchForm), typingInterval)

    })


    function submitform(form) {
        form.submit()

    }



});

</script>

{% endblock %}